# Generated by Django 3.0 on 2019-12-21 11:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tvrtke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_tvrtke', models.CharField(max_length=50)),
                ('vatid', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('street', models.CharField(blank=True, max_length=35, null=True)),
                ('street_number', models.CharField(max_length=10, verbose_name='Street number')),
                ('zip_code', models.CharField(max_length=15, verbose_name='Postanski broj')),
                ('city', models.CharField(max_length=30, verbose_name='Grad')),
                ('country', models.CharField(max_length=20, verbose_name='Drzava')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email adresa')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Napomena')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Kreirano')),
                ('modified', models.DateField(auto_now=True, verbose_name='Izmjenjeno')),
            ],
            options={
                'verbose_name': 'Kupci',
            },
        ),
        migrations.CreateModel(
            name='TipTvrtke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_tvrtke', models.CharField(choices=[('D', 'Dobavaljač'), ('K', 'Kupac')], default='K', max_length=2)),
                ('tvrtka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kupci.Tvrtke', verbose_name='Tip tvrtke')),
            ],
        ),
        migrations.CreateModel(
            name='Kontakti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50, verbose_name='Ime')),
                ('prezime', models.CharField(max_length=50, verbose_name='Prezime')),
                ('titula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Titula')),
                ('pozicija', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pozicija')),
                ('odjel', models.CharField(blank=True, max_length=25, null=True, verbose_name='Odjel')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('phone_contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefon')),
                ('mobile_contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Mobitel')),
                ('napomena', models.TextField(blank=True, null=True, verbose_name='Napomena')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Kreirano')),
                ('modified', models.DateField(auto_now=True, verbose_name='Kreirano')),
                ('tvrtka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kupci.Tvrtke')),
            ],
        ),
    ]
